#!/bin/bash
#Repositório Privado necessário criar uma secret com as credencias

kubectl create secret docker-registry regcred \
  --docker-server=docker.io \
  --docker-username=aristeuayres \
  --docker-password=dckr_pat_drkmMByy3GboFjiH59McZmhLMm4 \
  --docker-email=aristeu_ayres@yahoo.com.br \
  -n dev

#Associar a secret ao Deployment

kubectl patch deploy python-app -n dev -p '{
  "spec": {
    "template": {
      "spec": {
        "imagePullSecrets": [{"name": "regcred"}]
      }
    }
  }
}'

